### PR TITLE
Allow reading different lengths of int

### PR DESCRIPTION
**Pull request by Lucki**
I've tested my stuff with dosbox and I needed smaller read lengths.

### CODE REVIEW

**Comment by christofsteel** [comment]
This is a very good idea, I would request, that you add a flag for signedness to it (defaults to False). This can be forwarded to the `int.from_bytes` function (https://docs.python.org/3/library/stdtypes.html#int.from_bytes). 
Also (if we're at it) we could make the `byteorder` configurable and also forward this to the `int.from_bytes` function. (Default could then be `sys.byteorder`)

**Comment by christofsteel** [comment]
So, I didn't want to mess with your forked version, but have a look at my `int_size` branch. Would something like this work for you? (I have no games, that require multi-level variables or smaller int sizes, so testing is limited for me)

**Comment by Lucki** [comment]
Sadly that branch just starts the game and pyautosplit just closes itself. I've changed `sptr` in my config to `memory`.

**Comment by Lucki** [comment]
Can I somehow see which absolute address ptrace tries to access? Maybe the starting point is different from what Cheat Engine uses.

**Comment by christofsteel** [comment]
This is unfortunate. Can you send me the config, that you are using? (Btw. maybe this is easier on an IM-Platform. Do you have matrix?)

**Comment by Lucki** [comment]
Add @raumende:matrix.org and delete this message afterwards :)

**Pull request closed without merging**
